### ISSUE TITLE
Version 1.4.0 gone in npm

### ISSUE THREAD

**Issue by NoExcuseForCode** [jfhbrook/node-ecstatic#257] opened 2019-05-03 07:32 UTC
One of our module has dependency on 1.4.0 which is not available in npm, Can you reinstate the same.

**Comment by haridsv** [comment] 2019-05-03 08:50
Duplicate of issue #255

**Comment by jfhbrook** [comment] 2019-05-03 13:49
https://github.com/jfhbrook/node-ecstatic/issues/255#issuecomment-489101365

Like this comment says, there are versions available in the 2 3 and 4 majors but not for v1.

**Closed by jfhbrook** 2019-05-03 13:49 UTC
